language: node_js
node_js:
    - "0.12"

before_script:
    - npm install -g grunt-cli@0.1.x
    - npm install --quiet
    - npm install -g mocha
    - npm install -g istanbul

script:
    - grunt
    - istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec --recursive && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
